EBLL:
  IF_ON: True
  CODE_SIZE: 512
  LAMBDA: 0.01
MODEL:
  DEVICE_ID: 1
  IF_IBN_A: True
APEX:
  IF_ON: True
TEST:
  RUN_ID: 22
  IF_RE_RANKING: False
CONTINUATION:
  T: 10.0
EVAL:
  EPOCH_PERIOD: 1
OPTIMIZER:
  BASE_LR: 0.000035
LOSS:
  IF_LEARNING_WEIGHT: False
WARMUP:
  STEPS: (70, 100, 130)
TRAIN:
  LOG_ITER_PERIOD: 10