EBLL:
  IF_ON: True
  CODE_SIZE: 512
  LAMBDA: 0.01
MODEL:
  DEVICE_ID: 1
  IF_IBN_A: True
APEX:
  IF_ON: True
TEST:
  RUN_ID: 22
  IF_RE_RANKING: False
CONTINUATION:
  T: 10.0
  DATASET_NAME: 'market1501'
EVAL:
  EPOCH_PERIOD: 30
OPTIMIZER:
  BASE_LR: 0.000035
LOSS:
  IF_LEARNING_WEIGHT: False
DATASET:
  NAME: 'dukemtmc'